<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address1</name>
   <tag></tag>
   <elementGuidId>33838fd5-5bdc-4665-8f81-094f2e0aea26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;NewAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-AddressLine1&quot;]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
