<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_selectproducergroup</name>
   <tag></tag>
   <elementGuidId>e83c4075-6d41-4e77-bddf-1b252f9efd4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-ProducerSelectionInputSet-group-groupMenuIcon&quot;]/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
