<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_savedraft</name>
   <tag></tag>
   <elementGuidId>2ba4e39a-f18c-404d-912a-7e9bec24743b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;SubmissionWizard-SubmissionWizard_PreQualificationScreen-JobWizardToolbarButtonSet-Draft&quot;]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
