<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Quote</name>
   <tag></tag>
   <elementGuidId>616d3fe8-75a1-43f8-885d-00c30bea5ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;SubmissionWizard-SubmissionWizard_PreQualificationScreen-JobWizardToolbarButtonSet-QuoteTypeToolbarButtonSet-Quote&quot;]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
