<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_searchresults_select</name>
   <tag></tag>
   <elementGuidId>49a49b02-a641-4a99-8a38-8e5ccc653257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;GroupSearchPopup-GroupSearchPickerScreen-GroupSearchPickerResultsLV-3-_Select&quot;]/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
