<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_groupname</name>
   <tag></tag>
   <elementGuidId>cff7017b-9f77-403c-a27c-c1b2ca176d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;GroupSearchPopup-GroupSearchPickerScreen-GroupSearchDV-GlobalContactNameInputSet-Name&quot;]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
