<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_lastname</name>
   <tag></tag>
   <elementGuidId>e4882d1e-f511-45b0-abf7-66aeccfbeb5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;NewAccount-NewAccountScreen-NewAccountSearchDV-GlobalPersonNameInputSet-LastName&quot;]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
